# Generated by Django 4.1.7 on 2023-02-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0002_userprofile_address_userprofile_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picode',
            new_name='pincode',
        ),
    ]
