# Generated by Django 4.1.7 on 2023-02-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0003_rename_picode_userprofile_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
