# Generated by Django 4.1.7 on 2023-02-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0004_userprofile_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
