# Generated by Django 4.1.7 on 2023-02-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0006_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
