# Generated by Django 4.1.7 on 2023-02-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0010_alter_userprofile_mobile_alter_userprofile_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
