# Generated by Django 4.1.7 on 2023-02-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0012_alter_userprofile_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
