# Generated by Django 4.1.7 on 2023-02-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0013_alter_userprofile_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.TextField(null=True),
        ),
    ]
