# Generated by Django 4.1.7 on 2023-02-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0015_alter_userprofile_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Banglore', 'Banglore'), ('Hubli', 'Hubli'), ('Kannur', 'Kannur'), ('Ernakulam', 'Ernakulam'), ('Kozhikkode', 'Kozhikkode'), ('Madurai', 'Madurai'), ('Coimbator', 'Coimbator'), ('Hydrabad', 'Hydrabad')], max_length=20, null=True),
        ),
    ]
