# Generated by Django 4.1.7 on 2023-02-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0018_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Kannur', 'Kannur'), ('Madurai', 'Madurai'), ('Kozhikkode', 'Kozhikkode'), ('Ernakulam', 'Ernakulam'), ('Hubli', 'Hubli'), ('Banglore', 'Banglore'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hydrabad', 'Hydrabad'), ('Coimbator', 'Coimbator')], max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Kannur', 'Kannur'), ('Madurai', 'Madurai'), ('Kozhikkode', 'Kozhikkode'), ('Ernakulam', 'Ernakulam'), ('Hubli', 'Hubli'), ('Banglore', 'Banglore'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hydrabad', 'Hydrabad'), ('Coimbator', 'Coimbator')], max_length=20, null=True),
        ),
    ]
