# Generated by Django 4.1.7 on 2023-02-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0019_alter_address_city_alter_address_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Kannur', 'Kannur'), ('Madurai', 'Madurai'), ('Coimbator', 'Coimbator'), ('Ernakulam', 'Ernakulam'), ('Hubli', 'Hubli'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Banglore', 'Banglore'), ('Hydrabad', 'Hydrabad'), ('Kozhikkode', 'Kozhikkode')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Kannur', 'Kannur'), ('Madurai', 'Madurai'), ('Coimbator', 'Coimbator'), ('Ernakulam', 'Ernakulam'), ('Hubli', 'Hubli'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Banglore', 'Banglore'), ('Hydrabad', 'Hydrabad'), ('Kozhikkode', 'Kozhikkode')], max_length=20, null=True),
        ),
    ]
