# Generated by Django 4.1.7 on 2023-03-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0024_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Banglore', 'Banglore'), ('Kozhikkode', 'Kozhikkode'), ('Hubli', 'Hubli'), ('Ernakulam', 'Ernakulam'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hydrabad', 'Hydrabad'), ('Coimbator', 'Coimbator'), ('Kannur', 'Kannur'), ('Madurai', 'Madurai')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Banglore', 'Banglore'), ('Kozhikkode', 'Kozhikkode'), ('Hubli', 'Hubli'), ('Ernakulam', 'Ernakulam'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hydrabad', 'Hydrabad'), ('Coimbator', 'Coimbator'), ('Kannur', 'Kannur'), ('Madurai', 'Madurai')], max_length=20, null=True),
        ),
    ]
