# Generated by Django 4.1.7 on 2023-03-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0027_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Banglore', 'Banglore'), ('Kannur', 'Kannur'), ('Madurai', 'Madurai'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hubli', 'Hubli'), ('Kozhikkode', 'Kozhikkode'), ('Hydrabad', 'Hydrabad'), ('Coimbator', 'Coimbator'), ('Ernakulam', 'Ernakulam')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Banglore', 'Banglore'), ('Kannur', 'Kannur'), ('Madurai', 'Madurai'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hubli', 'Hubli'), ('Kozhikkode', 'Kozhikkode'), ('Hydrabad', 'Hydrabad'), ('Coimbator', 'Coimbator'), ('Ernakulam', 'Ernakulam')], max_length=20, null=True),
        ),
    ]
