# Generated by Django 4.1.7 on 2023-03-06 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0028_address_phone_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Coimbator', 'Coimbator'), ('Ernakulam', 'Ernakulam'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hydrabad', 'Hydrabad'), ('Banglore', 'Banglore'), ('Hubli', 'Hubli'), ('Kozhikkode', 'Kozhikkode'), ('Madurai', 'Madurai')], max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Mobile number should only contain digits', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Coimbator', 'Coimbator'), ('Ernakulam', 'Ernakulam'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hydrabad', 'Hydrabad'), ('Banglore', 'Banglore'), ('Hubli', 'Hubli'), ('Kozhikkode', 'Kozhikkode'), ('Madurai', 'Madurai')], max_length=20, null=True),
        ),
    ]
