# Generated by Django 4.1.7 on 2023-03-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0033_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Kozhikkode', 'Kozhikkode'), ('Banglore', 'Banglore'), ('Coimbator', 'Coimbator'), ('Madurai', 'Madurai'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kannur', 'Kannur'), ('Ernakulam', 'Ernakulam')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Kozhikkode', 'Kozhikkode'), ('Banglore', 'Banglore'), ('Coimbator', 'Coimbator'), ('Madurai', 'Madurai'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kannur', 'Kannur'), ('Ernakulam', 'Ernakulam')], max_length=20, null=True),
        ),
    ]
