# Generated by Django 4.1.5 on 2023-03-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0043_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Hydrabad', 'Hydrabad'), ('Madurai', 'Madurai'), ('Hubli', 'Hubli'), ('Coimbator', 'Coimbator'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Ernakulam', 'Ernakulam'), ('Kannur', 'Kannur'), ('Kozhikkode', 'Kozhikkode'), ('Banglore', 'Banglore')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Hydrabad', 'Hydrabad'), ('Madurai', 'Madurai'), ('Hubli', 'Hubli'), ('Coimbator', 'Coimbator'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Ernakulam', 'Ernakulam'), ('Kannur', 'Kannur'), ('Kozhikkode', 'Kozhikkode'), ('Banglore', 'Banglore')], max_length=20, null=True),
        ),
    ]
