# Generated by Django 4.1.7 on 2023-03-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0051_banner_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Banglore', 'Banglore'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Ernakulam', 'Ernakulam'), ('Hydrabad', 'Hydrabad'), ('Kannur', 'Kannur'), ('Hubli', 'Hubli'), ('Coimbator', 'Coimbator'), ('Madurai', 'Madurai'), ('Kozhikkode', 'Kozhikkode')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Banglore', 'Banglore'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Ernakulam', 'Ernakulam'), ('Hydrabad', 'Hydrabad'), ('Kannur', 'Kannur'), ('Hubli', 'Hubli'), ('Coimbator', 'Coimbator'), ('Madurai', 'Madurai'), ('Kozhikkode', 'Kozhikkode')], max_length=20, null=True),
        ),
    ]
