# Generated by Django 4.1.7 on 2023-03-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0052_banner_title_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Hubli', 'Hubli'), ('Kannur', 'Kannur'), ('Madurai', 'Madurai'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Ernakulam', 'Ernakulam'), ('Banglore', 'Banglore'), ('Coimbator', 'Coimbator'), ('Hydrabad', 'Hydrabad'), ('Kozhikkode', 'Kozhikkode')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Hubli', 'Hubli'), ('Kannur', 'Kannur'), ('Madurai', 'Madurai'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Ernakulam', 'Ernakulam'), ('Banglore', 'Banglore'), ('Coimbator', 'Coimbator'), ('Hydrabad', 'Hydrabad'), ('Kozhikkode', 'Kozhikkode')], max_length=20, null=True),
        ),
    ]
