# Generated by Django 4.1.7 on 2023-03-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0053_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Hubli', 'Hubli'), ('Banglore', 'Banglore'), ('Madurai', 'Madurai'), ('Coimbator', 'Coimbator'), ('Kozhikkode', 'Kozhikkode'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kannur', 'Kannur'), ('Ernakulam', 'Ernakulam'), ('Hydrabad', 'Hydrabad')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Hubli', 'Hubli'), ('Banglore', 'Banglore'), ('Madurai', 'Madurai'), ('Coimbator', 'Coimbator'), ('Kozhikkode', 'Kozhikkode'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kannur', 'Kannur'), ('Ernakulam', 'Ernakulam'), ('Hydrabad', 'Hydrabad')], max_length=20, null=True),
        ),
    ]
