# Generated by Django 4.1.7 on 2023-03-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0057_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Banglore', 'Banglore'), ('Ernakulam', 'Ernakulam'), ('Kozhikkode', 'Kozhikkode'), ('Hydrabad', 'Hydrabad'), ('Madurai', 'Madurai'), ('Kannur', 'Kannur'), ('Hubli', 'Hubli'), ('Coimbator', 'Coimbator')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Banglore', 'Banglore'), ('Ernakulam', 'Ernakulam'), ('Kozhikkode', 'Kozhikkode'), ('Hydrabad', 'Hydrabad'), ('Madurai', 'Madurai'), ('Kannur', 'Kannur'), ('Hubli', 'Hubli'), ('Coimbator', 'Coimbator')], max_length=20, null=True),
        ),
    ]
