# Generated by Django 4.1.7 on 2023-03-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0058_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Kannur', 'Kannur'), ('Coimbator', 'Coimbator'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Kozhikkode', 'Kozhikkode'), ('Madurai', 'Madurai'), ('Banglore', 'Banglore'), ('Ernakulam', 'Ernakulam')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Kannur', 'Kannur'), ('Coimbator', 'Coimbator'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Kozhikkode', 'Kozhikkode'), ('Madurai', 'Madurai'), ('Banglore', 'Banglore'), ('Ernakulam', 'Ernakulam')], max_length=20, null=True),
        ),
    ]
