# Generated by Django 4.1.7 on 2023-03-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0059_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kannur', 'Kannur'), ('Coimbator', 'Coimbator'), ('Madurai', 'Madurai'), ('Banglore', 'Banglore'), ('Ernakulam', 'Ernakulam'), ('Hubli', 'Hubli'), ('Hydrabad', 'Hydrabad'), ('Kozhikkode', 'Kozhikkode')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kannur', 'Kannur'), ('Coimbator', 'Coimbator'), ('Madurai', 'Madurai'), ('Banglore', 'Banglore'), ('Ernakulam', 'Ernakulam'), ('Hubli', 'Hubli'), ('Hydrabad', 'Hydrabad'), ('Kozhikkode', 'Kozhikkode')], max_length=20, null=True),
        ),
    ]
