# Generated by Django 4.1.5 on 2023-04-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0063_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Coimbator', 'Coimbator'), ('Hubli', 'Hubli'), ('Hydrabad', 'Hydrabad'), ('Ernakulam', 'Ernakulam'), ('Madurai', 'Madurai'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kozhikkode', 'Kozhikkode'), ('Kannur', 'Kannur'), ('Banglore', 'Banglore')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Coimbator', 'Coimbator'), ('Hubli', 'Hubli'), ('Hydrabad', 'Hydrabad'), ('Ernakulam', 'Ernakulam'), ('Madurai', 'Madurai'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kozhikkode', 'Kozhikkode'), ('Kannur', 'Kannur'), ('Banglore', 'Banglore')], max_length=20, null=True),
        ),
    ]
