# Generated by Django 4.1.5 on 2023-04-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0063_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Ernakulam', 'Ernakulam'), ('Kozhikkode', 'Kozhikkode'), ('Banglore', 'Banglore'), ('Kannur', 'Kannur'), ('Hubli', 'Hubli'), ('Coimbator', 'Coimbator'), ('Hydrabad', 'Hydrabad'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Madurai', 'Madurai')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Ernakulam', 'Ernakulam'), ('Kozhikkode', 'Kozhikkode'), ('Banglore', 'Banglore'), ('Kannur', 'Kannur'), ('Hubli', 'Hubli'), ('Coimbator', 'Coimbator'), ('Hydrabad', 'Hydrabad'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Madurai', 'Madurai')], max_length=20, null=True),
        ),
    ]
