# Generated by Django 4.1.7 on 2023-02-21 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0007_remove_product_images_remove_productimage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product',
            new_name='name',
        ),
    ]
