# Generated by Django 4.1.7 on 2023-02-21 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0008_rename_product_productimage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='name',
            new_name='product',
        ),
    ]
