# Generated by Django 4.1.7 on 2023-02-22 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0010_remove_productimage_product_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
