# Generated by Django 4.1.7 on 2023-02-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0013_remove_product_image_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='proimage'),
        ),
    ]
