# Generated by Django 4.1.7 on 2023-02-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0015_rename_image_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='image',
        ),
    ]
