# Generated by Django 4.1.7 on 2023-02-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0017_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imag',
            field=models.ImageField(null=True, upload_to='proimage'),
        ),
    ]
