# Generated by Django 4.1.7 on 2023-02-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0020_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='images',
        ),
        migrations.AddField(
            model_name='productimage',
            name='images',
            field=models.ManyToManyField(to='adminhome.product'),
        ),
    ]
