# Generated by Django 4.1.7 on 2023-02-27 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0022_productimage_product_remove_productimage_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imag',
        ),
    ]
