# Generated by Django 4.1.7 on 2023-03-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0023_remove_product_imag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
