# Generated by Django 4.1.7 on 2023-03-04 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0025_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock',
        ),
    ]
