# Generated by Django 4.1.7 on 2023-03-10 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0027_productvarient_product_varient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='varient',
        ),
        migrations.AddField(
            model_name='productvarient',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminhome.product'),
        ),
        migrations.AddField(
            model_name='productvarient',
            name='stock',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
