# Generated by Django 4.1.7 on 2023-03-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0028_remove_product_stock_remove_product_varient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvarient',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
