# Generated by Django 4.1.7 on 2023-03-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0030_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='varient',
            field=models.CharField(blank=True, choices=[('Wood', 'Wood'), ('Steel', 'Steel')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='ProductVarient',
        ),
    ]
