# Generated by Django 4.1.7 on 2023-03-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0032_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='varient',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
