# Generated by Django 4.1.7 on 2023-03-10 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0034_product_varient_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='varient',
        ),
        migrations.CreateModel(
            name='ProductVarient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varient', models.CharField(max_length=20, null=True)),
                ('productvar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminhome.product')),
            ],
        ),
    ]
