# Generated by Django 4.1.7 on 2023-03-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0035_remove_product_varient_productvarient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='ProductVarient',
        ),
    ]
