# Generated by Django 4.1.7 on 2023-03-11 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0036_alter_product_name_delete_productvarient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVarient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='varient_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminhome.productvarient'),
            preserve_default=False,
        ),
    ]
