# Generated by Django 4.1.7 on 2023-03-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0037_productvarient_product_varient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
