# Generated by Django 4.1.5 on 2023-03-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0039_remove_product_varient_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvarient',
            old_name='varname',
            new_name='proname',
        ),
        migrations.AddField(
            model_name='productvarient',
            name='varientname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
