# Generated by Django 4.1.7 on 2023-03-11 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0040_rename_varname_productvarient_proname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvarient',
            name='proname',
        ),
        migrations.AddField(
            model_name='product',
            name='varname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminhome.productvarient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvarient',
            name='catname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminhome.category'),
            preserve_default=False,
        ),
    ]
