# Generated by Django 4.1.7 on 2023-03-13 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0042_remove_productvarient_catname'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarient',
            name='catname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminhome.category'),
            preserve_default=False,
        ),
    ]
