# Generated by Django 4.1.7 on 2023-03-14 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0043_productvarient_catname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='varname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminhome.productvarient'),
        ),
    ]
