# Generated by Django 4.1.7 on 2023-03-17 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0045_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='varname',
        ),
        migrations.RemoveField(
            model_name='productvarient',
            name='catname',
        ),
        migrations.AddField(
            model_name='productvarient',
            name='proname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminhome.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvarient',
            name='varprice',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productvarient',
            name='varstock',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
