# Generated by Django 4.1.7 on 2023-03-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0046_remove_product_price_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvarient',
            name='varprice',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
