# Generated by Django 4.1.7 on 2023-03-04 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cartitem_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='count',
            new_name='quantity',
        ),
    ]
