# Generated by Django 4.1.7 on 2023-03-17 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0047_remove_productvarient_varprice_product_price'),
        ('shop', '0006_coupon_order_usercoupon_payment_orderproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='provar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminhome.productvarient'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='provar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminhome.productvarient'),
        ),
    ]
