# Generated by Django 4.1.7 on 2023-03-24 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0048_alter_productvarient_proname'),
        ('shop', '0009_orderproduct_varient'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='productimage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminhome.productimage'),
        ),
    ]
