# Generated by Django 4.1.7 on 2023-03-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orderproduct_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='refund_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
