# Generated by Django 4.1.7 on 2023-04-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_order_wallet_amt_alter_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='wallet_amt',
        ),
    ]
